name: AoDS Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.event.head_commit.message, 'docs') }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17

      - name: install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          cd ../frontend
          npm install

      - name: test frontend
        working-directory: frontend
        run: |
          npm run lint
          npm run build
          npm run test -- --no-watch --no-progress --watch=false --code-coverage --browsers=ChromeHeadlessCI

      - name: test backend
        working-directory: backend
        run: pytest -vv --cov=app --cov-report=term-missing --cov-report=xml tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}